version: "3.7"
services:

    mysql:
        image: mysql:5.7
        container_name: lab-mysql
        working_dir: /application
        command: --init-file /application/db/db.sql --character-set-server=${MYSQL_CHARSET} --collation-server=utf8_general_ci --max_allowed_packet=1000000000 --net_buffer_length=1000000000
        volumes:
            - .:/application
            - ./docker/lab-mysql/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8082:3306"
    
    webserver:
        build: ./docker/lab-webserver/
        container_name: lab-webserver
        hostname: lab-webserver
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_CHARSET=${MYSQL_CHARSET}
        volumes:
            - ./src:/var/www/html/lab
            - ./docker/lab-webserver/facialRecognitionLogin:/home/html/facialRecognitionLogin
            - ./docker/lab-webserver/logs:/var/log/apache2

        ports:
            - "80:80"
        depends_on:
            - mysql
        links:
            - mysql

    # smtp:
    #     image: gessnerfl/fake-smtp-server
    #     container_name: lab-smtp
    #     working_dir: /application
    #     volumes:
    #         - ./smtp:/application
    #     ports:
    #         - "5080:5080"
    #         - "5081:5081"
